### ISSUE TITLE
multiple instances support

### ISSUE THREAD

**Issue by m-sallam** [ncthbrt/nact#95] opened 2021-01-03 08:13 UTC
A support for multiple instances meaning that an in memory messaging queue would not work. So, an added implementation for an external messaging queue (RabbitMQ, or Apache Kafka) would allow such a thing to happen.
Also, we would need to make sure there is only one actor alive for each id. We could do that by keeping track in a key value store instead of in memory map. and an event that fires when an actor shuts down or a ping for the actor that indicates it's still alive.

## Expected Behavior
- when starting the system. there would be an option for an external message queue
- actors fire an event when they gracefully shut down / a ping event (to update the ttl value in the key value store for example)

## Current Behavior
currently messages for each actor are stored and sent in memory

## Possible Solution
- adding support for external messaging queues
- actors would have an indicator that they are still alive

## Context
I am trying to run Nact in an environment that horizontally scales, so when that happens the state is not guaranteed to be correct.
Also running Nact in a multiple node system (swarm, kubernetes) would result into the same issue.

**Comment by ncthbrt** [comment] 2021-01-03 16:25
Apologies. I'm going to have to close this issue. 

The feedback that there is demand for clustering or multi instanfe support is valuable, and hopefully something we plane to look into this year however the suggested solution of just throwing infrastructure at the problem is somewhat antithetical to nact design principles. 

If we were to add support for clustering, using queuing systems like Kafka or rabbitnq would only be supported as an extension.

**Closed** 2021-01-03 16:26 UTC
