### ISSUE TITLE
Actors in the same system do not run in parallel

### ISSUE THREAD

**Issue by yunmin97** [ncthbrt/nact#76] opened 2019-12-29 03:43 UTC
## Code like:
```
const {start, spawnStateless, dispatch} = require('nact');

// create actor system
const system = start();

// a complex calculation model
function intensive_computation() {
    let intensity = 100000000;
    while (intensity > 0) {
        // intensity--;
    }
}

// create an actor(actorA)
let actorA = spawnStateless(system,
    function (msg, ctx) {
        console.log("i am %s, msg: %s", this.name, msg.word);
        console.time(this.name);
        intensive_computation();
        console.timeEnd(this.name);
    },
    "compute-intensive-actor"
);

// create an actor(actorB)
let actorB = spawnStateless(system,
    function (msg, ctx) {
        console.log("i am %s, msg: %s", this.name, msg.word);
    },
    "other-actor"
);

// start actor A
dispatch(actorA, {
    word: 'start computing...'
});

// start actor B
dispatch(actorB, {
    word: 'i need some cpu resource...'
});
```

## Issue description
actorB  will never be executed before actorA finished.  the time-consuming actor will blocks all the other actors.
so...  actors in the same system do not run in parallel??

## Environment
* Operating System:   windows 10
* Nact version:   v7.2.2
* Nodejs version:   v10.15.3

**Comment by ncthbrt** [comment] 2019-12-29 06:24
Hi there,

As I explained in a previous issue, nact does not support multi threading
within a single system.

It uses cooperative multitasking and thus like most JavaScript code
requires that you structure long running computations in a way that allows
it to yield to other requests in the event loop. This limitation of the
JavaScript runtime is also why NodeJS famously has non blocking APIs.

To get your example to work, you'd need to either launch a worker process
that did the computation, and use the actor to handle the result. You could
probably make a generic worker actor quite easily. Alternatively you'd
could restructure `intensive_computation()` so that it returns a promise
with periodic awaits. An example I think would be adding an `await
Promise.fromResult()` inside the while loop.

Technically there *are* ways to do multiprocessing in NodeJs, and I've
experimented with a number of them including WebWorkers and process
forking. However they completely kill the ergonomics of this library as
they add a lot of implicit requirements in the way in which you structure
and write your code. For example having to write your entire actor function
to be inline to the actor creation, or having the actor function be written
in a separate file that can be individually required.

Because of these oddities, I made the decision to prioritize predictability
and user friendliness of the API, in the knowledge that for users who need
to utilize threads, actors could be used to create elegant abstractions
around the threading primitives.

**Comment by ncthbrt** [comment] 2019-12-29 06:45
@yunmin97 I'm going to close this and your other issue, as the behaviour you're seeing is 'by design". I'm not at a PC right now, but if you join the discord, I can try my best to walk you through creating an actor that supports multiprocessing. Here is an invite link https://discord.gg/uxhFdDSnk

**Closed by ncthbrt** 2019-12-29 06:45 UTC
